version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
build:
  verbosity: minimal
  
  after_build:
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\j1GUI-try\Debug\Motor2D.exe"
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\j1GUI-try\Game"
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\j1GUI-try\*.dll"
- 7z a SpikeFromAppveyor.zip "%APPVEYOR_BUILD_FOLDER%\README.md"
